/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactId = IDL.Nat;
export const Timestamp = IDL.Int;
export const ContactMessage = IDL.Record({
  'id' : ContactId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const LeadId = IDL.Nat;
export const Lead = IDL.Record({
  'id' : LeadId,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'serviceTag' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});
export const ContactMessageInput = IDL.Record({
  'name' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const LeadInput = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'serviceTag' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'submitContactMessage' : IDL.Func(
      [ContactMessageInput],
      [ContactMessage],
      [],
    ),
  'submitLead' : IDL.Func([LeadInput], [Lead], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactId = IDL.Nat;
  const Timestamp = IDL.Int;
  const ContactMessage = IDL.Record({
    'id' : ContactId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const LeadId = IDL.Nat;
  const Lead = IDL.Record({
    'id' : LeadId,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'serviceTag' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  const ContactMessageInput = IDL.Record({
    'name' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const LeadInput = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'serviceTag' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'submitContactMessage' : IDL.Func(
        [ContactMessageInput],
        [ContactMessage],
        [],
      ),
    'submitLead' : IDL.Func([LeadInput], [Lead], []),
  });
};

export const init = ({ IDL }) => { return []; };