/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ContactId = bigint;
export interface ContactMessage {
  'id' : ContactId,
  'name' : string,
  'createdAt' : Timestamp,
  'message' : string,
  'phone' : string,
}
export interface ContactMessageInput {
  'name' : string,
  'message' : string,
  'phone' : string,
}
export interface Lead {
  'id' : LeadId,
  'city' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'serviceTag' : [] | [string],
  'phone' : string,
}
export type LeadId = bigint;
export interface LeadInput {
  'city' : string,
  'name' : string,
  'serviceTag' : [] | [string],
  'phone' : string,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'getContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'submitContactMessage' : ActorMethod<[ContactMessageInput], ContactMessage>,
  'submitLead' : ActorMethod<[LeadInput], Lead>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];